import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


import Header from "./_components/header";
import AuthProvider from "./_providers/auth";
import CartProvider from "./_providers/cart-provider";
import { Toaster } from "./_components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`${inter.className} dark`}>
      <body className={inter.className}>
        <AuthProvider>
          <CartProvider>
            <Header />
            {children}
          </CartProvider>
        </AuthProvider>
      </body>
      <Toaster />
    </html>
  );
}
